name: oidc-poc

on:
    push:
        branches:
            - '*'

jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Get id token
              run: |
                    ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                    "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
                    echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
                    echo "$ID_TOKEN"
            
            - name: Exchange token with access (Optional if you still need access token)
              env:
                    ID_TOKEN: ${{env.ID_TOKEN}}
                    JFROG_PLATFORM_URL: https://hts2.jfrog.io
              run: |
                    EXCHANGE_RESPONSE=$(curl -XPOST -H "Content-Type: application/json" "https://hts2.jfrog.io/access/api/v1/oidc/token" -d \
                    "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"github\"}")
                    
                    echo "Token Exchange Response: $EXCHANGE_RESPONSE"
                    ACCESS_TOKEN=$(echo "$EXCHANGE_RESPONSE" | jq .access_token | tr -d '"')
                    
                    echo "Access Token: $ACCESS_TOKEN"
                    
                    if [ -z "$ACCESS_TOKEN" ]; then
                      echo "Error: ACCESS_TOKEN is empty!"
                      exit 1
                    fi
                    
                    echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

            - name: Install JFrog CLI
              run: |
                    curl -fL https://getcli.jfrog.io | sh
                    sudo mv jfrog /usr/local/bin/

            - name: Configure JFrog CLI with OIDC Token
              env:
                 ID_TOKEN: ${{ env.ID_TOKEN }}
              run: |
                    # Set the Artifactory URL and use OIDC token for authentication
                    jfrog config add my-artifactory --url https://hts2.jfrog.io/artifactory --access-token $ID_TOKEN

            - name: Ping Artifactory API with JFrog CLI (jf rt ping)
              run: |
                    echo "Pinging Artifactory using JFrog CLI..."
                    jfrog rt ping --url https://hts2.jfrog.io/artifactory
